Javascript/javascript1/week2
MaherHussain/hyf-homework pull request #5
Opened 2020-05-21 16:16 UTC by MaherHussain

2020-05-23 08:12 UTC, zuhairtaha approved these changes
- Perfect Maher. I added some feedback, you can check and update then I'll check again 🙂
- I highly recommend you to use [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) extension for vscode to format your code and make it easier to read.
This is a [good video](https://www.youtube.com/watch?v=iGWwmVmvFPk) to see how to add it

2020-05-23 08:12 UTC, zuhairtaha commented on javascript/javascript1/week2/formalNameEx.js
> +function getFullname (firstname, lastname, useFormalName ){
Give a default value for `useFormalName` like this
```js
function getFullname (firstname, lastname, useFormalName = false) {
```

2020-05-23 08:12 UTC, zuhairtaha commented on javascript/javascript1/week2/formalNameEx.js
> +   console.log( firstname, lastname );
you don't have to log it, just return is enough

2020-05-23 08:12 UTC, zuhairtaha commented on javascript/javascript1/week2/formalNameEx.js
> +});
This section is redundant, remove it. You can use codepen link to test your function, but it is not required to be in the homework

2020-05-23 08:12 UTC, zuhairtaha commented on javascript/javascript1/week2/eventDay.js
> +function getEventWeekday(eventDayNum) {
This is fine. But can you try to use `day` as a string parameter for this function instead of a number. Then this function can be called like this
```js
getEventWeekday('sunday');
```

2020-05-23 08:12 UTC, zuhairtaha commented on javascript/javascript1/week2/weatherWear.js
> +let output;
it is better to put the variable inside the function. Imagin you will copy the function to somewhere else. It will not work because `output` is out of the function. This issue called `side effect` in programming, you can search and read more about it. the function should not change the value of something out of it. _sometimes we need that and no other way_ but in general, this should be avoided

2020-05-23 08:12 UTC, zuhairtaha commented on javascript/javascript1/week2/weatherWear.js
> +         output = "it's winter  and it's very cold,  you have to wear coat and hat and cloves ";
you can directly return the string instead of assigning the value and return it at the end. Example
```js
return  "it's winter  and it's very cold,  you have to wear coat and hat and cloves ";
```
The same for all of the rest assigning lines

2020-05-23 08:12 UTC, zuhairtaha commented on javascript/javascript1/week2/weatherWear.js
> +    else if( 5 <  temperature && temperature< 15 ){
- what about if the temperature is `15`. Include it in conditions using `<=` or `>=`

2020-05-23 08:12 UTC, zuhairtaha commented on javascript/javascript1/week2/studentManager.js
> +        result = "welcome Queen Margrethe you have place between us ";
هههه ضحكني هالكود تبعك. 
قحطتلو للطالب وحطيت الملكة محلو. المطلوب بالسؤال انو تخليها تنضاف حتى لو مكتمل العدد 😀
على كل حال رح خلي تعليقاتي انجليزي من شان اذا المدرسين بالصف قرؤوهم.
والله يسعدو معلم ماهر

2020-05-23 08:12 UTC, zuhairtaha commented on javascript/javascript1/week2/studentManager.js
> + if(studentName == "Queen"){
- use `===` to compare type and value
- what if someone used the function and write it `"queen"`? To make it more safe let us make the variable studentName in lower case then compare
```js
if (studentName.toLocaleLowerCase() === "queen") {
```

2020-05-23 08:12 UTC, zuhairtaha commented on javascript/javascript1/week2/studentManager.js
> +        return fales;
you don't have to return a boolean value. just use `return` to stop function here and don't continue

2020-05-23 08:12 UTC, zuhairtaha commented on javascript/javascript1/week2/studentManager.js
> +        result = "Cannot add more students to class 07";
This is an unreachable code because there is `return` in the line before it. You can log this sentence `"Cannot add more students to class 07"` then return
```js
  console.log("Cannot add more students to class 07");
  return;
```

2020-05-23 08:12 UTC, zuhairtaha commented on javascript/javascript1/week2/studentManager.js
> +    else if(class07Students.includes(studentName)){
perfect

2020-05-23 08:12 UTC, zuhairtaha commented on javascript/javascript1/week2/studentManager.js
> +    else if(studentName == " "){
- use `===` always
- you can use `trim()` on strings in javascript to remove empty spaces.
```js
if (studentName.trim() === "")
```

2020-05-23 08:12 UTC, zuhairtaha commented on javascript/javascript1/week2/studentManager.js
> +    return alert (result);
remove this line

2020-05-23 08:12 UTC, zuhairtaha commented on javascript/javascript1/week2/weatherWear.js
> +console.log(userwear);
![image](https://i.imgur.com/dhVn2hs.png)
I tried to enter the queen many times. and it works. Fix this please

2020-05-23 08:12 UTC, zuhairtaha commented on javascript/javascript1/week2/candyEx.js
> +        return console.log(n);
Log it directly without a variable and without return
```js
console.log("candy type is not exist")
```

2020-05-23 08:12 UTC, zuhairtaha commented on javascript/javascript1/week2/candyEx.js
> +    }
This is fine but can write a short way.
```js
return totalPrice < amountToSpend;
```

2020-05-23 08:13 UTC, zuhairtaha requested changes
Please check feedback and update it

2020-05-23 23:31 UTC, MaherHussain commented on javascript/javascript1/week2/studentManager.js
> +        result = "welcome Queen Margrethe you have place between us ";
.   هههههههههههههههه ع راسي معلم زهير

2020-05-27 21:57 UTC, zuhairtaha requested changes
can you check this and compare with your results at `eventDay` question:
```js
function getEventWeekday(day) {
  const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  const today = new Date().getDay();
  return days[(day + today) % 7];
}
```

2020-05-27 21:57 UTC, zuhairtaha commented on javascript/javascript1/week2/studentManager.js
> +  return console.log(result);
Never add `return` before `console.log`. Remove it

2020-05-27 21:57 UTC, zuhairtaha commented on javascript/javascript1/week2/studentManager.js
> +  } else if (studentName.trim === "") {
`trim` is a method (function) not a property so you have to add parenthesis to call it `trim()`

2020-05-27 21:57 UTC, zuhairtaha commented on javascript/javascript1/week2/weatherWear.js
> +  } else if (15 < temperature && temperature < 25) {
It is better to use `<=` and `>=` at some of them. Notice that there is no condition to consider `15` and the same for the rest.

2020-05-27 21:57 UTC, zuhairtaha commented on javascript/javascript1/week2/studentManager.js
> +  } else if (class07Students.length >= 6) {
You can use one `if` to fix all like this
```js
if (class07Students.length >= 6 && studentName.toLocaleLowerCase() !== "queen" ) {
  console.log("Cannot add more students to class 07");
  return;
}
```
This will check if we have 6 sutdents and the name of student is not queen. 
`toLocaleLowerCase()` will change the string to lower case, then will help us to accept "Queen" and "queen" as the same string.

2020-05-27 21:57 UTC, zuhairtaha commented on javascript/javascript1/week2/candyEx.js
> +}
This should return boolean as required at homework. But no problem for now. I accept this.

2020-05-27 21:57 UTC, zuhairtaha commented on javascript/javascript1/week2/eventDay.js
> +}
can you check this and compare with your results:
```js
function getEventWeekday(day) {
  const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  const today = new Date().getDay();
  return days[(day + today) % 7];
}
```

2020-05-27 23:07 UTC, merged